"""
Strategy Base Class

All trading strategies inherit from this abstract base.

Key principles:
- Strategies generate signals (LONG, SHORT, EXIT, NO_TRADE)
- Strategies are regime-aware (use regime classifier)
- Strategies are stateless (receive all needed data)
- Strategies integrate with risk engine
"""

from abc import ABC, abstractmethod
from enum import Enum
from dataclasses import dataclass
from typing import Optional, Dict, Any
import pandas as pd
import logging

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types."""
    LONG = "long"           # Enter long position
    SHORT = "short"         # Enter short position (not used in spot trading)
    EXIT = "exit"           # Exit current position
    NO_TRADE = "no_trade"   # Do nothing


@dataclass
class TradingSignal:
    """
    Trading signal generated by strategy.
    
    Attributes:
        signal_type: Type of signal
        confidence: Signal confidence (0-1)
        entry_price: Suggested entry price
        stop_loss: Suggested stop loss price
        take_profit: Optional take profit price
        regime: Current market regime
        reason: Human-readable reason for signal
        metadata: Additional strategy-specific data
    """
    signal_type: SignalType
    confidence: float
    entry_price: float
    stop_loss: Optional[float] = None
    size: float = 0.0
    take_profit: Optional[float] = None
    regime: Optional[str] = None
    reason: str = ""
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        """Validate signal after initialization."""
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be in [0, 1], got {self.confidence}")
        
        if self.entry_price <= 0:
            raise ValueError(f"Entry price must be positive, got {self.entry_price}")
        
        if self.stop_loss is not None and self.stop_loss <= 0:
            raise ValueError(f"Stop loss must be positive, got {self.stop_loss}")
        
        if self.metadata is None:
            self.metadata = {}


class Strategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategies must implement:
    - generate_signal(): Analyze data and produce signal
    - get_name(): Return strategy name
    - is_regime_compatible(): Check if regime is suitable
    """
    
    def __init__(self):
        """Initialize strategy."""
        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")
        self.signals_generated = 0
        self.last_signal: Optional[TradingSignal] = None
    
    @abstractmethod
    def generate_signal(
        self,
        data: pd.DataFrame,
        current_position: Optional[str] = None
    ) -> TradingSignal:
        """
        Generate trading signal based on current data.
        
        This is the CORE method every strategy must implement.
        
        Args:
            data: DataFrame with OHLCV, features, and regime data
                  Must include at minimum:
                  - close, high, low, volume
                  - regime, regime_confidence
                  - Any strategy-specific features
            current_position: Current position ('long', 'short', None)
        
        Returns:
            TradingSignal with recommended action
            
        Example:
            >>> signal = strategy.generate_signal(df)
            >>> if signal.signal_type == SignalType.LONG:
            ...     # Enter long position
        """
        pass
    
    @abstractmethod
    def get_name(self) -> str:
        """
        Get strategy name.
        
        Returns:
            Human-readable strategy name
        """
        pass
    
    @abstractmethod
    def is_regime_compatible(self, regime: str) -> bool:
        """
        Check if strategy can trade in given regime.
        
        Args:
            regime: Market regime (trend, range, chaos, no_trade)
            
        Returns:
            True if strategy can trade in this regime
            
        Example:
            >>> strategy.is_regime_compatible('trend')
            True
            >>> strategy.is_regime_compatible('chaos')
            False
        """
        pass
    
    def validate_data(self, data: pd.DataFrame) -> bool:
        """
        Validate that data has required columns.
        
        Args:
            data: DataFrame to validate
            
        Returns:
            True if data is valid
            
        Raises:
            ValueError: If required columns missing
        """
        if data.empty:
            raise ValueError("Provided data is empty")

        required_columns = ['close', 'high', 'low', 'volume', 'regime']
        missing = [col for col in required_columns if col not in data.columns]
        
        if missing:
            raise ValueError(f"Missing required columns: {missing}")
        
        if len(data) == 0:
            raise ValueError("DataFrame is empty")
        
        return True
    
    def record_signal(self, signal: TradingSignal) -> None:
        """
        Record signal for tracking.
        
        Args:
            signal: Generated signal
        """
        self.signals_generated += 1
        self.last_signal = signal
        
        self.logger.info(
            f"Signal #{self.signals_generated}: {signal.signal_type.value} "
            f"(confidence: {signal.confidence:.2f}, regime: {signal.regime})"
        )
    
    def get_statistics(self) -> Dict[str, Any]:
        """
        Get strategy statistics.
        
        Returns:
            Dictionary with strategy stats
        """
        return {
            'name': self.get_name(),
            'signals_generated': self.signals_generated,
            'last_signal': self.last_signal.signal_type.value if self.last_signal else None,
        }
    
    def __repr__(self) -> str:
        """String representation."""
        return f"{self.__class__.__name__}(signals={self.signals_generated})"


class SimpleStrategy(Strategy):
    """
    Example simple strategy implementation.
    
    This is a template showing how to implement the Strategy interface.
    Real strategies should inherit from Strategy directly.
    """
    
    def generate_signal(
        self,
        data: pd.DataFrame,
        current_position: Optional[str] = None
    ) -> TradingSignal:
        """Generate simple signal (always NO_TRADE)."""
        self.validate_data(data)
        
        latest = data.iloc[-1]
        
        signal = TradingSignal(
            signal_type=SignalType.NO_TRADE,
            confidence=1.0,
            entry_price=latest['close'],
            regime=latest.get('regime'),
            reason="Example strategy - always returns NO_TRADE"
        )
        
        self.record_signal(signal)
        return signal
    
    def get_name(self) -> str:
        """Get strategy name."""
        return "Simple Example Strategy"
    
    def is_regime_compatible(self, regime: str) -> bool:
        """Check regime compatibility."""
        return regime in ['trend', 'range']  # Example: avoid chaos


def main():
    """Test strategy framework."""
    print("=" * 60)
    print("STRATEGY FRAMEWORK TEST")
    print("=" * 60)
    
    # Create example data
    import numpy as np
    
    n = 100
    df = pd.DataFrame({
        'close': 42000 + np.random.randn(n) * 500,
        'high': 42500 + np.random.randn(n) * 500,
        'low': 41500 + np.random.randn(n) * 500,
        'volume': 100 + np.abs(np.random.randn(n) * 20),
        'regime': ['trend'] * 50 + ['range'] * 50,
        'regime_confidence': np.random.uniform(0.6, 0.9, n),
    })
    
    # Test simple strategy
    strategy = SimpleStrategy()
    
    print(f"\n📊 Strategy: {strategy.get_name()}")
    print(f"   Compatible with 'trend': {strategy.is_regime_compatible('trend')}")
    print(f"   Compatible with 'chaos': {strategy.is_regime_compatible('chaos')}")
    
    # Generate signal
    print("\n🎯 Generating signal...")
    signal = strategy.generate_signal(df)
    
    print(f"   Signal type: {signal.signal_type.value}")
    print(f"   Confidence: {signal.confidence:.2f}")
    print(f"   Entry price: R{signal.entry_price:.2f}")
    print(f"   Regime: {signal.regime}")
    print(f"   Reason: {signal.reason}")
    
    # Statistics
    print("\n📈 Strategy statistics:")
    stats = strategy.get_statistics()
    for key, value in stats.items():
        print(f"   {key}: {value}")
    
    print("\n" + "=" * 60)
    print("✅ Strategy framework test complete")


if __name__ == "__main__":
    main()